#ifndef BSP_INC_FIR_FILTER_COEF_H_
#define BSP_INC_FIR_FILTER_COEF_H_

// ESKİ SÜRÜCÜYÜ ÇAĞIRAN O SATIRI SİLDİK VE YERİNE FİLTRE BOYUTUNU MANUEL YAZDIK
#define FIR_TAPS 258U

extern float fir_coef[FIR_TAPS];

#endif /* BSP_INC_FIR_FILTER_COEF_H_ */
